name: Xamarin CI

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        cd ..
        cd ..
        msbuild DinnerSelection.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
