name: Android Build

on: [push, pull_request]

jobs: 
  Android:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - name: Android
      run: |
        nuget restore
        msbuild DinnerSelection/DinnerSelection.Android/DinnerSelection.Android.csproj /verbosity:normal /t:Rebuild /p:Configuration=Debug
